Qual 73 add das configuration
SkillsFundingAgency/hmrc-apprenticeship-levy-api-stub pull request #3
Opened 2019-12-06 11:41 UTC by DannyGB

Adds the standard das configuration infrastructure to the project
To get this to work you will also need to add configuration to the local storage emulator

2019-12-06 14:25 UTC, MarieDale3 approved these changes

2019-12-12 14:01 UTC, MarieDale3 commented on src/SFA-DAS-HMRC-API-Stub/Data/Configuration/Declaration.cs
> +            //builder.ToTable("Declarations");
Class could be deleted

2019-12-12 14:01 UTC, MarieDale3 commented on src/SFA-DAS-HMRC-API-Stub/Data/Configuration/EmployerReference.cs
> +            //builder.Property(x => x.Data).HasColumnName(@"Data").HasColumnType("varchar(max)").IsRequired();
Delete class

2019-12-12 14:07 UTC, MarieDale3 requested changes
Delete a couple of classes

2019-12-12 14:13 UTC, DannyGB commented on src/SFA-DAS-HMRC-API-Stub/Data/Configuration/Declaration.cs
> +            //builder.ToTable("Declarations");
Correct, will remove

2019-12-12 14:14 UTC, DannyGB commented on src/SFA-DAS-HMRC-API-Stub/Data/Configuration/EmployerReference.cs
> +            //builder.Property(x => x.Data).HasColumnName(@"Data").HasColumnType("varchar(max)").IsRequired();
Will remove

2019-12-12 14:21 UTC, MarieDale3 approved these changes

2019-12-12 14:21 UTC, merged